<?php 
defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$form=$this->form;

    //$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
	$url_submit =  $this->url(array('module'=>'product','controller'=>'Index','action'=>'test'));
    $url_cancel =  $this->url(array('module'=>'product','controller'=>'Index','action'=>'index'));
    $url_check =  $this->url(array('module'=>'product','controller'=>'Index','action'=>'check'));
    $url_new = $this->url(array('module'=>'product','controller'=>'Index','action'=>'add'));
?>						  
<title><?php echo $tr->translate("ADD_NEW_ITEM");?></title>
<body>
<div class="wrapper">
    <div class="clear"></div>
    <div class="right">
    	
			    <form id="frm" action="<?php echo $url_submit; ?>" method="post" enctype="multipart/form-data">
			    	<div class="contorl-cus">
			    		<?php //echo $this->control ;?>
			        	<?php  $frmctrol=$this->control ;?>
			        	<a href="<?php echo $url_new; ?>" class="new"><?php echo $tr->translate("NEW");?></a>
			        	<?php echo $frmctrol->getElement('Save');?>
			        	<?php echo $frmctrol->getElement('Version');?>
			        	<a href="<?php echo $url_cancel ?>" class="cancel"><?php echo $tr->translate("CANCEL");?></a>
			    		<input onclick="closeMe()" type="submit" name='btn_close' value="<?php echo $tr->translate("CLOSE");?>" class="close" />
			        </div>
			        <div class="all-tab">
			        <div id="tabs" class="tabs-bottom">
						<ul style="border-top:1px solid #999;">
							<li><a href="#tabs-1"><?php echo $tr->translate("PRODUCT_INFO");?></a></li>
							<li><a href="#tabs-2"><?php echo $tr->translate("MOVE_MENT");?></a></li>
							<li><a href="#tabs-3"><?php echo $tr->translate("ORDER_HISTORY");?></a></li>
						</ul>
						<div class="tabs-spacer"></div>
					<div id="tabs-1">	
				        <div class="de-font">
				        	<div class="view-table">
				        		<div class="head_form">
					        		<?php echo $tr->translate("Product info");?>
					        	</div>
					        	<div class="contain_form">
					        		<div class="shadow">
							        	<table>
							                <tr>
							                    <td width="15%"><?php echo $tr->translate("ITEM_NAME"); ?></td>
							                    <td width="30%"><?php echo $form->getElement('txt_name'); ?></td>
							                    <td colspan="2"> 
								                    <div id = "feedback">
													</div>
												</td>
							                </tr>
							                <tr>
							                	<td><?php echo $tr->translate("ITEM_CODE");?></td>
							                	<td><?php echo $form->getElement("txt_code");?></td>
							                	<td></td>
							                	<td></td>
							                </tr>
							                <tr>
							                    <td><?php echo $tr->translate("CATEGORY"); ?></td>
							                    <td id="new_currency_info"><?php echo $form->getElement('category');?></td>
							                    <td><?php echo $tr->translate("PHOTO");?></td>
							                    <td>
														 <?php echo $form->getElement("photo");?>
							                    </td>
							                </tr>
							                <tr>
							                    <td><?php echo $tr->translate("TYPE"); ?></td>
							                    <td><?php echo $form->getElement('type');?></td>
							                    <td colspan="2"></td>
							                </tr>
							                <tr>
							                    <td><?php echo $tr->translate("NORMAL_PRICE");?></td>
							                    <td><?php echo $form->getElement('price');?></td>
							                    <td></td>
							                    <td></td>
							                </tr>
							                <tr>
							                    <td><?php echo $tr->translate("REMARK"); ?></td>
							                    <td><?php echo $form->getElement('remark');?></td>
							                    <td></td>
							                    <td></td>
							                </tr>
					                 </table>
					               </div>
					        	</div><!-- end .contain_form -->
					        	
					        	<div id="div2" style="display:block">
				        		</div>
				        	</div><!-- end of .view-table -->
				        	
				        	<br/>
					        	 	    <div class="transfer" style="width: 100%;">
					        	 	    	<div class="view-table">
									        	<div class="head_form">
									        		<?php echo $tr->translate("ITEM_LOCATION_LIST");?>
									        	</div>
									        	<div class="contain_form">
									        		<table class="collape" id="table_order" style="width: 50%;">
														<tr height="25px">
															<td class="sub-tdheader"><?php echo $tr->translate("NUM");?></td>
															<td class="sub-tdheader"><?php echo $tr->translate("LOCATION_NAME");?></td>
															<td class="sub-tdheader"><?php echo $tr->translate("CUR_QTY");?></td>
															<td class="sub-tdheader"><?php echo $tr->translate("CUR_QTY");?></td>
														</tr>
													</table>
													<input type="hidden" id="identity" name="identity" />
													<table>
														<tr>
															<td class="new-row">
																<div class="btn">
																	<button class="positive" type="button" id="new_item"  name= "new_followup" value="<?php echo $tr->translate("NEW")?>">
																				&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
																	</button>
																</div>
															</td>
														</tr>
													</table>
									        	</div>
									    	</div>
			                      		</div>	
								  <div id="div1" style="display:none" >
											
								  </div>
				        </div><!-- end of de-font -->
			        </div><!-- end of tab1 -->
						<div id="tabs-2">
							<div class='view-table'>
								<table border='1px' style="border:1px solid #ccc;" width='100%'>
									<tr class="head-table">
										<td><?php echo $tr->translate("TYPE_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_ADD_CAP");?></td>
										<td><?php echo $tr->translate("CUSTOMER_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_DATE_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_STATUS_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_TOTAL_CAP");?></td>
										<td><?php echo $tr->translate("QTY_CAP");?></td>
										<td><?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
										<td><?php echo $tr->translate("SUBTOTAL_CAP");?></td>
									</tr>
									<?php 
									$num=0;
									 	for($i=0; $i<=12 ; $i++)
									 	{
									 		$num=1-$num; 
									 		echo"<tr class='row-table{$num}'>";
									 			echo"<td>$i</td>"; 
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 		echo"</tr>";
									 	}
									 echo"<tr class='row-table0'>";
									 			echo"<td>".$tr->translate("QTY_ON_HAND")."</td>";
									 			echo"<td colspan='2'></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 
									 echo"</tr>";
									 echo"<tr class='row-table0'>";
												 echo"<td>".$tr->translate("QTY_ON_SOLD")."</td>";
												 echo"<td colspan='2'></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
									 echo"</tr>";
									echo"<tr class='row-table0'>";
												 echo"<td>".$tr->translate("QTY_ON_ORDER")."</td>";
												 echo"<td colspan='2'></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
												 echo"<td></td>";
									 	
									 echo"</tr>";
									?>
									
								</table>
							</div>
						</div><!-- end tab 4 -->
					<div id="tabs-3">
							<div class='view-table'>
								<table width='100%' border="1px" style="border:1px solid #ccc;" >
									<tr class="head-table">
										<td><?php echo $tr->translate("TYPE_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_ADD_CAP");?></td>
										<td><?php echo $tr->translate("CUSTOMER_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_DATE_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_STATUS_CAP");?></td>
										<td><?php echo $tr->translate("ORDER_TOTAL_CAP");?></td>
										<td><?php echo $tr->translate("QTY_CAP");?></td>
										<td><?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
										<td><?php echo $tr->translate("SUBTOTAL_CAP");?></td>
									</tr>
									<?php 
									$num=0;
									 	for($i=0; $i<=12 ; $i++)
									 	{
									 		$num=1-$num; 
									 		echo"<tr class='row-table{$num}'>";
									 			echo"<td>$i</td>"; 
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 			echo"<td></td>";
									 		echo"</tr>";
									 	}
									
									?>
									
								</table>
							</div>
						</div><!-- tab3 -->
					</div>
				</div>
			   </div><!-- end main tab -->
			      
			        <div class="clear"></div>
		    </form>
		
    </div><!--end right-->
</div><!--end wrapper-->
 <!-- end new Location -->
<div id="overlay-location" class="web_dialog_overlay"></div>
		<?php $form_stock = $this->form_addstock; ?>
		<div id="dialog-location" class="web_dialog">
		<form id="frm-location">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_LOCATION");?>
				<a href="#" id="btnCloseLocation" class="cancelDailog"></a>
			</div>
			<div class="shadow">
				<table style="width: 100%; margin:0 auto; padding:10px;">
					<tr>
						<td><?php echo $tr->translate("LOCATION_NAME");?></td>
						<td width="30%"><?php echo $form_stock->getElement("StockName");?></td>
						<td><?php echo $tr->translate("CON_NAME");?></td>
						<td width="30%"><?php echo $form_stock->getElement("ContactName");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("CON_NUM");?></td>
						<td><?php echo $form_stock->getElement("ContactNumber");?></td>
						<td><?php echo $tr->translate("STOCK_ADD");?></td>
						<td><?php echo $form_stock->getElement("location_add");?></td>
					</tr>
					<tr>
						<td colspan="2"></td>
						<td><?php echo $tr->translate("DESC");?></td>
						<td><?php echo $form_stock->getElement("description");?></td>
					</tr>
					<tr>
						<td colspan="2" style="text-align: center;">
							<input id="btn_add" Onclick="addNewLocation()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
							<input id="btncancel_location" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
						</td>
						<td colspan="2"></td>
					</tr>
		       </table>
	       </div>
	     </form>
 </div>
<!-- for add category -->
 <div id="overlay" class="web_dialog_overlay"></div>
<?php $frm_cate= $this->form_category;?>
		<div id="dialog" class="web_dialog">
		<form id="frm1">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_CATE");?>
				<a href="#" id="btnClose" class="cancelDailog"></a>
			</div>
			<table style="width:100%; margin:0 auto;">
				
				<tr>
					<td><?php echo $tr->translate("MAIN_CAT");?></td>
					<td><?php echo $frm_cate->getElement("main_category");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CATEGORY_NAME");?></td>
					<td><?php echo $frm_cate->getElement("category_name");?></td>
				</tr>
				<tr>
					<td></td>
					<td><?php echo $frm_cate->getElement("remark_order");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addNewCategory()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancel" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
				</tr>
	       </table>
	     </form>
 </div>
 
<script>
//action when click on add/delete of followup
var index5 = 0;
var option5 = '<?php echo $this->locations; ?>';

var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
// add order record
function addRow() {
	selectValue();
	//var value = $("#location_id_1 :selected").attr('label');
	index5++; var first = index5;
	template='<tr id="row_order_'+index5+'">';
	var inp = '';
	if(index5 == 1) {
		template+='<td class="quater-input">&nbsp;</td>';
		//test();
	} else {
		template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		//inp = '<input type="text" style="position: relative;margin-top: -15px; top:-15px; width: 211px;" onchange="AddLocation('+index5+')" class="validate[required] ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" value="'+value+'">';
	}
	
	template+='<td class="quater-input"><div class="select_d"><select Onchange="AddLocation('+index5+')" data-placeholder="'+option5+'" class="validate[required] chzn-select-deselect"  id="location_id_'+index5+'" name="location_id_'+index5+'" >'+option5+'</select>'+inp+'</div></td>'; 
	template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" class="validate[required,custom[number]]" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td class="quater-input"><select name="test_'+index5+'" id="test_'+index5+'" onChange="Getvalue('+index5+')" data-placeholder="This is Value here" style="width:80px;" class="chzn-select-deselect"><option></option> <option value="1">American Black Bear</option> <option value="2">American Black Bear</option></select></td>';
	
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#orderFrm").validationEngine();

	//if(first == 1){	value = $("#location_id_1 :selected").attr('label');}
	//Getselect();
	
	
}



//add default row or record when click
$('#new_item').click(addRow);
//add default row or record when ready
jQuery(document).ready(function(){
	addRow();
});
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();

	// total price
}
var record_index= 1;
function AddLocation(index){
	var location_id = $("#location_id_"+index).val();
	if(location_id==-1){
		     record_index = index;
		     AddNewLocation(true);
			 
	  }	
}

function showPopupCategory(){
	category_id = $("#category").val();
	if(category_id==-1){
		ShowDialog(true);
	}
}
</script>
<!-- for select get value -->
<script>
    function displayVals() {
      var singleValues = $("#single").val();
     
      var multipleValues = $("#multiple").val() || [];
      $("p").html("<b>Single:</b> " +"<br />"+singleValues);
      return singleValues
    }
    $("select").change(displayVals);
    displayVals();
</script>
<script type = "text/javascript">
			$(document).ready(function(){ //when the document is ready, run the function
				$('#feedback').load('<?php echo $url_check?>').show();
				
				$('#txt_name').keyup(function(){

					$.post('<?php echo $url_check;?>', { username: frm.txt_name.value },
						function(result){
							$('#feedback').html(result).show();
						});
					
				});
			});
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName,#ContactName');
		$.ajax({
				url: "<?php echo $url_add_location;?>",
				type: "post",
				data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
			success: function(data){
				val = $.parseJSON(data); 
				//alert("Data has been add successed!");
				$('#location_id_'+record_index).append($("<option></option>").attr("label",location_name).attr("value",val['LocationId']).attr("data-placeholder",location_name).attr("selected",true).text(location_name)); 
				selectValue();
				document.getElementById("frm-location").reset();
				HideDialoglocation();
			},
			error:function(){
				alert("faile insert");
				$("#result").html('There is error while submit');
		   }
	    });
			 
}
//for add new category
<?php $url_add_cate =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-category')); ?>
function addNewCategory(){
	/*
	$('#category').parent().find(".selectize-dropdown-content div.selected").removeClass("selected");
    $('#category').parent().find(".selectize-dropdown-content").append('<div data-value="aaaa" data-selectable="" class="option  selected">aaaa</div>');
    $('#category').parent().find(".selectize-input div").html("aaa");
    return;*/
	
	var parent_id = $("#main_category").val();
	var category_name = $("#category_name").val();
	validate_text('#category_name');//validate_text($string_array);$string_array="#a,#b,#c";
	
		$.ajax({
	        url: "<?php echo $url_add_cate;?>",
	        type: "post",
	        data: {'parent_id':parent_id,'category_name':category_name},
	        success: function(data){
	            val = $.parseJSON(data);
	           $('#category').append($("<option></option>").attr("value",val['CategoryId']).attr("selected",true).text(category_name));
	          
		        // $('#category').next().val(category_name);
	            document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });	
}

</script>		
</body>
</html>
        <select name="country" id="country" onChange="Getvalue()" data-placeholder="Your Favorite Type of Bear" style="width:350px;" class="chzn-select-deselect">
          <option value=""></option>
          <option value="1">American Black Bear</option>
          <option value="2">Asiatic Black Bear</option>
          <option value="3">Brown Bear</option>
          <option value="4">Giant Panda</option>
          <option value="5">Sloth Bear</option>
          <option value="6">Sun Bear</option>
          <option value="7">Polar Bear</option>
          <option value="8">Spectacled Bear</option>
        </select> 
<script>
	function Getvalue(index){
		var x = $("#test_"+index).val();
		alert(x);
		}
	
</script>
