<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle( $tr->translate('LOGIN') .' | '.  $tr->translate('RSMK')); 
	echo $this->headTitle();
	$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
?>
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL;?>/css/interface.css" media="all" />	
<script type="text/javascript" src="<?php echo BASE_URL;?>/js/jquery-ui-1.8.20.custom.min.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL;?>/js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL;?>/js/jquery-1.7.2.min.js"></script>

<script type="text/javascript">
<!--
$(document).ready(function(){
	$("#errorpanel").hide();
	<?php if(!empty($this->msg)) :?>
		$("#errorpanel").show();
	<?php endif;?>
	
	
	
});
function resetform(){
	 $('#errorpanel').hide();
	 var validator = $("#myform").validate();
	 validator.resetForm();
}
//-->
</script>

<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<head>
<link rel="shortcut icon" href="<?php echo BASE_URL;?>/images/resolvo.ico" type="image/x-icon"/>
<link type="text/css" href="<?php echo BASE_URL;?>/css/template.css" rel="stylesheet" />
<link type="text/css" href="<?php echo BASE_URL;?>/css/style.css" rel="stylesheet"/>
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL;?>/css/layout.css" media="all" />
<link  rel="stylesheet" type="text/css" href="<?php echo BASE_URL;?>/css/include.css" media="all" />
<link type="text/css" href="<?php echo BASE_URL;?>/css/custom-theme/jquery-ui-1.8.20.custom.css" rel="stylesheet" />
<style>
	*{ margin:0; padding:0;}
	input[type="text"],input[type="password"]{ border:1px solid #ccc !important; height: 25px  !important;}
body
{
	background:#e7f0f9;
	font-family:"Lucida Grande", Tahoma, Arial, Verdana, sans-serif;
	font-size:small;
	margin:0 0 16px;
	text-align:center;
}
.top-login{
	width:100%; background:#339900;height:30px;
	-moz-box-shadow: 1px -5px 5px #064217;
	-webkit-box-shadow: 1px -5px 5px #064217;
	box-shadow: 1px -5px 5px #064217;
}
{

.my-cover{ width:100%; background:#006600; padding:50px 0;}	
	.content-top{
}
</style>
</head>

<body><!-- oncontextmenu="return false" -->



</body>
<script>
document.onmousedown=disableclick;
function disableclick(event)
{
  if(event.button==2)
   {
     return false;    
   }
}
</script>

<!DOCTYPE html>
<html>
<head>
<title>Layout Example</title>
<script type="text/javascript" src="<?php echo BASE_URL;?>/js/jquery-latest.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL;?>/js/jquery.layout-latest.js"></script>
<script type="text/javascript">
$(document).ready(function () {
	$('body').layout({ applyDemoStyles: true });
});
</script>
</head>
<body>
<div class="ui-layout-north" >
<div class="content-top" style="border: 1px solid #56A00E;background: #74b042;
	color: #fff;
	font-weight: bold;
	text-shadow: 0 1px 1px #335413;
	background-image: -webkit-gradient(linear, left top, left bottom, from(#74b042), to(#56A00E));
	background-image: -webkit-linear-gradient(#74b042, #56A00E);
	background-image: -moz-linear-gradient(#74b042, #56A00E);
	background-image: -ms-linear-gradient(#74b042, #56A00E);
	background-image: -o-linear-gradient(#74b042, #56A00E);
	background-image: linear-gradient(#74b042, #56A00E);">
<a href="<?php echo $this->baseUrl();?>/index/index" style="float:left;">
	<img src="<?php echo BASE_URL; ?>/images/logo-img.png" class="cso-logo" style="padding: 5px;" />
</a>
<h2 class="title-system">STOCK INVENTORY SYSTEM</h2>

</a>
<div style="clear:both;"></div>
</div>
</div>
<div class="ui-layout-west">West</div>
<div class="ui-layout-center">
		<table align="center" bgcolor="#006600"  cellspacing="30px" style="margin:0 auto; border:#fff;">
			<tr style="background: #fff;">
				<td>
				<div class="top-login"></div>
					<div id="login">
						
					    <h1><?php echo $tr->translate('WELCOME_RSMK');?></h1>
					
					    <h3><?php //echo $tr->translate('LOGIN_SEC');?></h3>
						<div id="errorpanel"  class="ui-state-error ui-corner-all" style="padding: 2px; font-size: 12px; text-align: center;" >
							<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
								<label id="summary"><?php echo $this->msg;?></label></p>
						</div>
					    <div id="more-information">
					        <p>
					             <div id="re-information">
					             	<form id="loginform" action="" method="post">
					             	<table border="0" cellpadding="2px" cellspacing="1px">
								        <tr>           
								            <td>
								                <table width="100%" cellpadding="3px" style="font-size: 12px;">
								                    <tr height="35px">
								                        <td><?php echo $tr->translate("EMAIL");?>:  </td>
								                        <td><input type="text" size="32" id="txt_email" name="txt_email" /></td>
														<td style="color:blue; font-weight:normal;">(<?php echo $tr->translate('NOT_SENSITIVE');?>)</td>
								                    </tr>
								                    <tr height="35px">
								                        <td><?php echo $tr->translate("PASSWORD");?>:  </td>
								                        <td><input type="password" size="32" id="txt_password" name="txt_password"  /></td>
														<td style="color:red;font-weight:normal;">(<?php echo $tr->translate('SENSITIVE');?>)</td>
								                    </tr>
								                </table>
								            </td>
								        </tr>
								        <tr height="50px">          
								            <td align="center" class="btn">
								                <input class="btn_submit ui-button" type="submit" value="Log in" size="25" />
												<input class="btn_submit ui-button" type="reset" onclick="resetform()" value="Reset" size="25"/>
								            </td>
								        </tr>
								    </table>
								    </form>
					    		</div>
					    	</p>
					    </div>
					</div>
				</td>
			</tr>
		</table>
</div>
<!-- top -->
<div class="ui-layout-east">East</div>
<!-- bottom -->
<div class="ui-layout-south">

<div class="content-bottom">
	<table width="100%" height="100%">
		<tr>
			<td width="50%"></td>
			<td width="50%" align="left">
				<p class="lable-footer" style="padding-top:7px; font-size: 15px;"><b>Power By <a class="link_url" href="http://www.resolvocam.com/">Resolvo(Cambodia) Co., Ltd.</a></b><br />
					Address: Borei Akasajar BA 7, Sangkat Kakab, Khan Dangkor, Phnom Penh, Cambodia<br />
					Tel:(+855) 23 956 789 | Fax:(+855) 23 957 777<br />
					Website:<a class="link_url" href="http://www.resolvocam.com/" >www.resolvocam.com</a>
            </p>
			</td>
		</tr>
	</table>
</div>

</div>

</body>
</html>