<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage(); 
	$session_user=new Zend_Session_Namespace('auth');
	$request=Zend_Controller_Front::getInstance()->getRequest();
?>		
<style>
.branch_name{ 
	margin-left:-10px;margin-top:2px; background:#eeeeee;padding:10px;
	display: none;
	border:1px solid #006600;
	z-index: 1000;position: absolute;
}
.branch_name ul li a{line-height: 20px;}
.branch_name ul li:hover{text-decoration: underline;}

.my-user:hover .branch_name{ display: block;}

</style>	
<div class="header">
		<div class="cover-top">
		   		<div class="col-md-6">
		   			<img alt="" src="<?php echo $this->baseUrl();?>/images/add-new-products.png">
		   		</div>
		         		<?php 
		         			$title = $request->getModuleName() . "_"
									 . $request->getControllerName() ."_"
									 . $request->getActionName();
							$title = "MENU_" . strtoupper(str_replace("-", "_", $title));
		         		?>
		          <h2><?php //echo $tr->translate($title);?></h2>
		          <div class="blog-user col-md-6" >
			            <div class="my-user" style="float: right;"><?php echo $tr->translate('MENU_USERACCESS');?>
			            <a class="user_id" href="<?php echo $this->url(array('module'=>'rsvAcl','controller'=>'user','action'=>'change-password', 'id'=>$session_user->user_id));?>">
								<?php echo ucwords(strtolower($session_user->fullname));?>
								
						</a>
			           	<a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout', 'value'=>1));?>">
								<?php echo "| ".$tr->translate("MENU_SIGNOUT");?>
						</a>
						<a onclick="closeMe()" href="#">
								<?php echo "| ".$tr->translate("CLOSE_SYSTEM");?>
						</a>
						<?php if($session_user->level!=1 AND $session_user->level!=2): ?>
						<?php 
						$dbtable = new Product_Model_DbTable_DbGetBranch();
						$branchs = $dbtable->getBranchbyUser($session_user->user_id);
						?>
						<div class="branch_name">	
							<ul>
								<?php if(!empty($branchs)) foreach ($branchs as $key =>$value):?>
									<li><a href="<?php echo $this->url(array('module'=>'product','controller'=>'changeuser','action'=>'index', 'id'=>$value["location_id"]));?>"><?php echo $value["Name"]?></a></li>
								<?php endforeach;?>
							</ul>
						</div>
						<?php endif;?>
						
						
							
			           	</div>
		           </div>
	    </div>
</div><!--end of header-->