<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
	$urlNeed = $this->url(array('module'=>'distributor','controller'=>'customer-order','action'=>'show-item-for-choosing',
	));
	$url_submit =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'add-customer-quote'));
	$url_cancel =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'index'));
?>
<title><?php echo $tr->translate("ADD_SALES_QUOTE");?></title>
<div class="wrapper">
    <div class="clear"></div>
    <div class="contance">
    </div><!--end of contance-->
    <div class="left">
    </div><!--end of left-->
    <div class="right">
    	<form id="orderFrm" action="<?php echo $url_submit; ?>" method="post" enctype="multipart/form-data">
    	<div class="contorl-cus">
        	<?php //echo $this->control ;?>
        	<?php  $frmctrol=$this->control ;?>
        	<?php echo $frmctrol->getElement('New');?>
        	<?php echo $frmctrol->getElement('Save');?>
        	<?php echo $frmctrol->getElement('Copy');?>
        	<?php echo $frmctrol->getElement('Version');?>
        	<?php echo $frmctrol->getElement('Deactive');?>
        	<?php echo $frmctrol->getElement('Attact');?>
        	<a href="<?php echo $url_cancel ?>" class="cancel"><?php echo $tr->translate("CANCEL");?></a>
    		
        </div>
         <div class="style-form" style="padding:20px;">
			<div class="view-table">
				<div class="head_form">
					<?php echo $tr->translate("Customer info");?>
				</div>
			   	<div class="contain_form">
				        <table>
				                <tr>
				                	<td width="15%"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
				                    <td width="20%">
				                       <?php echo $form->getElement("customer_id");?>
				                    </td>
				                    <td width="15%"><?php echo $tr->translate("LOCATION_NAME");?></td>
				                    <td><?php echo $form->getElement("LocationId");?></td>
				                </tr>
				                <tr>
				                	<td><?php echo $tr->translate("CON_NAME");?></td>
				                    <td><?php echo $form->getElement('contact'); ?></td>      
				                     <td><?php echo ucwords($tr->translate("SALE_AGENT"));?></td>
				                    <td><?php echo $form->getElement("sales_ref"); ?></td>
				                </tr>
				                <tr>
				                	<td><?php echo $tr->translate("CON_NUM");?></td>
				                    <td><?php echo $form->getElement("txt_phone"); ?></td>
				                    <td><?php echo $tr->translate("ORDER");?><div id ="feedback"></div></td>
				                    <td width="15%"><?php echo $form->getElement("order");?></td>
				                </tr>
				                 <tr>
				                	<td><?php echo $tr->translate("DATE_ORDER");?></td>
				                    <td><?php echo $form->getElement("order_date"); ?></td>
				                    <td><?php echo $tr->translate("STATUS");?></td>
				                    <td><?php echo $form->getElement("quote");?></td>
				                </tr>
				                <tr>
				                	<td><?php echo $tr->translate("CUS_ADDRESS");?></td>
				                    <td><textarea  name="customer_add" id="customer_add" rows="3" cols="19"></textarea></td>
				                    <td></td>
				                    <td></td>
				                </tr>
				            </table>
			   	</div><!-- end of .contain_table -->
			</div><!-- end of .view-table -->	
		</div><!-- end of .style-form -->	
	<div style="padding:0px 20px 20px 20px;">
		<div class="head_form">
			<?php echo $tr->translate("CUSTOMER_ORDER_LIST");?>
		</div>
		<div class="contain_form">
			<table>
				<tr>
					<td valign="top" colspan="2">
						<div class="view-table">
			   			<table class="collape" id="table_order">
										<tr height="33px">
											<td class="sub-tdheader"><?php echo $tr->translate("DEL");?></td>
											<td class="sub-tdheader" width="100px"><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("QTY_ORDER_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("TOTAL_PRICE_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("DISCOUNT_CAP");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("SUB_TOTAL_CAP");?></td>
										</tr>
									</table>
								</div>
						<input type="hidden" id="identity" name="identity" />
						<table>
							<tr>
								<td class="new-row">
									<div class="btn">
										<button class="positive" type="button" id="new_item"  name= "new_followup" value="<?php echo $tr->translate("NEW");?>" >
											&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
										</button>
									</div>
								</td>
							</tr>
						</table>
						<table class="detail_table">
							<tr>
								<td class="total_label"><?php echo $tr->translate("NET-TOTAL");?></td>
								<td class="total_price"><?php echo $form->getElement('net_total');?></td>
							</tr>
							<tr>
								<td class="total_label"><?php echo $tr->translate("DISCOUNT");?></td>
								<td class="total_price"><?php echo $form->getElement('discount_type').$form->getElement('discount_value').' = '.$form->getElement('discount_real');?></td>
							</tr>
							<tr>
								<td class="total_label"><?php echo $tr->translate("ALL-TOTAL");?></td>
								<td class="total_price"><?php echo $form->getElement('all_total');?></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<div class="view-table">
					<table style="width:100%; margin:0 auto;">
		                <tr>
		                	<td width="15%"><?php echo $tr->translate("PAYMENT_METHOD");?></td>
		                    <td width="20%">
		                    	<?php echo $form->getElement("payment_name");?>
		                    </td>
		                    <td width="12%"></td>
		                    <td width="30%">
		                       
		                    </td>
		                    <td></td>
		                </tr>
		                <tr>
		                	<td><?php echo $tr->translate("CURRENTCY_TYPE");?></td>
		                    <td>
		                    	<?php echo $form->getElement("currency");?>
		                    </td>
		                    <td width="20%" rowspan="3"></td>              
		                    <td><?php echo $tr->translate("PAID");?></td>
		                    <td><?php echo $form->getElement("paid");?></td>
		                </tr>
		                <tr>
		                	<td><?php echo $tr->translate("REMARK");?></td>
		                    <td rowspan="2"><?php echo $form->getElement("remark");?></td>

		                    <td><?php echo $tr->translate("BALANCE");?></td>
		                    <td><?php echo $form->getElement("remain");?></td>
		                </tr>
		                <tr>
		                    <td></td>
		                    <td><input class="btn_submit" type="submit" value="<?php echo $tr->translate("CONVERT_TO_ORDER");?>" name="quote" /></td>
		                    <td></td>
		                </tr>
		            </table>	
		       </div>
			</div><!-- end of .contain_form -->	
			</div>
    	</form>
    </div><!-- end right -->
</div><!-- end wrapper -->
<div id="overlay" class="web_dialog_overlay"></div>
<?php $frm_product= $this->form_product;?>
		<div id="dialog" class="web_dialog">
		<form id="frm1">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_ITEM");?>
				<a href="#" id="btnClose" class="cancelDailog"></a>
			</div>
			<table style="width: 95%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("ITEM");?></td>
					<td><?php echo $frm_product->getElement("product_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("ITEM_CODE");?></td>
					<td><?php echo $frm_product->getElement("item_code");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("PRICE");?></td>
					<td><?php echo $frm_product->getElement("item_price");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $frm_product->getElement("remark_order");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addProduct()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancel" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
				</tr>
	       </table>
	     </form>
 </div>
<div id="overlay-vendor" class="web_dialog_overlay"></div>
<?php $frm_customer= $this->form_customer;?>
		<div id="dialog-vendor" class="web_dialog">
		<form id="frmvendor">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_CUSTOMER");?>
				<a href="#" id="btnClosevendor" class="cancelDailog"></a>
			</div>
			<table style="width: 98%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td width="70px"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
					<td><?php echo $frm_customer->getElement("txt_name");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $frm_customer->getElement("txt_contact_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CON_NUM");?></td>
					<td><?php echo $frm_customer->getElement("customer_phone");?></td>
					<td><?php echo $tr->translate("CUS_ADDRESS");?></td>
					<td rowspan="2"><?php echo $frm_customer->getElement("txt_address");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("EMAIL");?></td>
					<td><?php echo $frm_customer->getElement('txt_mail');?></td>
					<td></td>
				</tr>
				<tr>
					<td></td>
					<td></td>
					<td colspan="2">
						<input id="btn_add" Onclick="addNewCustomer()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancelVendor" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
					
				</tr>
	       </table>
	     </form>
 </div>
 <div id="overlay-location" class="web_dialog_overlay"></div>
		<?php $form_stock = $this->form_addstock; ?>
		<div id="dialog-location" class="web_dialog">
		<form id="frm-location">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_LOCATION");?>
				<a href="#" id="btnCloseLocation" class="cancelDailog"></a>
			</div>
			<table style="width: 95%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("LOCATION_NAME");?></td>
					<td><?php echo $form_stock->getElement("StockName");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $form_stock->getElement("ContactName");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CON_NUM");?></td>
					<td><?php echo $form_stock->getElement("ContactNumber");?></td>
					<td><?php echo $tr->translate("STOCK_ADD");?></td>
					<td><?php echo $form_stock->getElement("location_add");?></td>
				</tr>
				<tr>
					<td colspan="2"></td>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $form_stock->getElement("description");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addNewLocation()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btncancel_location" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
					<td colspan="2"></td>
				</tr>
	       </table>
	     </form>
 </div>
 
<script>
//action when click on add/delete of followup
var index5 = 0;
var option5 = '<?php echo $this->items; ?>';

var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var urlPrice = '<?php echo BASE_URL.'/distributor/order/getItemPrice'; ?>';
// add order record
function addRow() {
	index5++;
	var inp = '';
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	if(index5 == 1) {
		template+='<td class="quater-input">&nbsp;</td>';
	} else {
		template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		inp = '<input type="text" style="position: relative;margin-top: -15px; top:-15px; width: 211px;" onchange="AddLocation('+index5+')" class="validate[required] ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" value="">';
	}
	template+='<td class="quater-input"><select onChange="getCurrentPrice('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'</select>'+inp+'</td>';
	template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" style="width: 90px;" class="validate[required,custom[number]] input" id="qty_order_'+index5+'" name="qty_order_'+index5+'"/></td>';
	template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" style="width: 90px;" class="validate[required,custom[number]] input" id="price_'+index5+'" name="price_'+index5+'" /></td>';
	template+='<td class="quater-input"><input type="text" class="input100px input" readonly="readonly" id="total_'+index5+'" name="total_'+index5+'" /></span></td>';
	template+='<td class="quater-input"><input type="radio" onChange="calculatePrice('+index5+')" name="dis-type-'+index5+'"  id="dis-type-'+index5+'" value="2" />Fix Value &nbsp;<input type="radio" onChange="calculatePrice('+index5+')" name="dis-type-'+index5+'" id="dis-type2-'+index5+'" value="1" checked="checked" />% &nbsp;<input type="text"  onChange="calculatePrice('+index5+')" class="input70px input" id="dis-value'+index5+'" name="dis-value'+index5+'" /> =<input type="text" readonly="readonly" class="input70px input" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
	template+='<td class="quater-input"><input type="text" class="input100px input" readonly="readonly" id="after_discount'+index5+'" name="after_discount'+index5+'" /></td>';
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#orderFrm").validationEngine();
}

//add default row or record when click
$('#new_item').click(addRow);
//add default row or record when ready
jQuery(document).ready(function(){
	addRow();
});

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();

	// total price
	netTotal();
	doTotal();
}

function doTotal() {
	var discountType = $('input:radio[name="discount_type"]:checked').val();
	var discountValue = ($('#discount_value').val() == '')? 0 : $('#discount_value').val();
	var netTotal = ($('#net_total').val()=='')?0 : $('#net_total').val();
	var discountReal = 0;
	discountReal = (discountType == 1)? (netTotal * discountValue) / 100 : discountValue;
	$('#discount_real').val(discountReal);
	var allTotal = Number(netTotal)-Number(discountReal);
	$('#all_total').val(allTotal);
	$('#remain').val(allTotal)-$('#paid').val();
}
function doRemain() {
	// total for all record(total part)
	var total = $('#all_total').val();
	var paid = $('#paid').val();
	var remain = total-paid;
	$('#remain').val(remain);
}

function netTotal() {
	// total for all record(total part)
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#after_discount'+rowIDArray[n]).val());
	}
	$('#net_total').val(netTotal);
}


// Calculate price of order
function calculatePrice(index) {
	// total price
	var price = $('#price_'+index).val();
	var qty = $('#qty_order_'+index).val();
	var total = price * qty;
	$('#total_'+index).val(total);

	// discount of total price
	var disType = $('input:radio[name=dis-type-'+index+']:checked').val();
	var disValue = ($('#dis-value'+index).val() == '')? 0 : $('#dis-value'+index).val();
	var discount = (disType == 1)? total * disValue / 100 : disValue;
	$('#real-value'+index).val(discount);
	var lastTotal = $('#total_'+index).val() - discount;
	$('#after_discount'+index).val(lastTotal);
	// total price
	netTotal();
	doTotal();
}
</script>
<?php  $url_check =  $this->url(array('module'=>'salse','controller'=>'sales-order','action'=>'check'));?>
<script type = "text/javascript">
			$(document).ready(function(){ //when the document is ready, run the function
				$('#feedback').load('<?php echo $url_check?>').show();
				
				$('#order').keyup(function(){

					$.post('<?php echo $url_check;?>', { username: orderFrm.order.value },
						function(result){
							$('#feedback').html(result).show();
						});
					
				});
			});
</script>
<?php $url_getcurrentitem =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'get-customer-info')); ?>
<script>
var record_index= 1;
function getCustomerInfo(){
	var customer_id = $("#customer_id").val();
	if(customer_id==-1){
		  ShowVendorDialog(true);
		 
     }
	else{
	//var location_id = $("#LocationId").val();
		$.ajax({
	        url: "<?php echo $url_getcurrentitem;?>",
	        type: "post",
	        data: {'customer_id':customer_id},
	        success: function(data){
	            val = $.parseJSON(data);
	            $("#contact").val(val.contact_name);
	            $("#txt_phone").val(val.phone);
	            $("#customer_add").val(val.address);
	        },
	        error:function(){
	            alert("Please Select Vendor");
	            $("#result").html('There is error while submit');
	        }
	    });
	}
}
function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		     AddNewLocation(true);
			
	  }	
}
<?php $url_getcurrent_price =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'get-current-price')); ?>
var record_index= 1;
function getCurrentPrice(index){
	item_id = $("#item_id_"+ index).val();
	if(item_id==-1){
		     record_index = index;
			 ShowDialog(true);
	}
	else{
		$.ajax({
	        url: "<?php echo $url_getcurrent_price;?>",
	        type: "post",
	        data: {'item_id':item_id},
	        success: function(data){
	            //alert(data);
	            val = $.parseJSON(data);
	            $("#price_"+ index).val(val.price);
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });
	}
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
function addProduct(){
	var pro_name = $("#product_name").val();
	var pro_code = $("#item_code").val();
	var price = $("#item_price").val();
	var remark = $("#remark_order").val();
	validate_text('#product_name');
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'price':price,'remark':remark},
	        success: function(data){
	            val = $.parseJSON(data);
	            $('#item_id_'+record_index).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name)); 
	            $("#price_"+ record_index).val(price);
				$('#item_id_'+record_index).next().val(pro_name);
		        document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            alert("Insert Failed!");
	            $("#result").html('There is error while submit');
	        }
	    });	
}
<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add-customer')); ?>
function addNewCustomer(){
	var customer_name  = $("#txt_name").val();
	var contact = $("#txt_contact_name").val();
	var phone   = $("#customer_phone").val();
	var address = $("#txt_address").val();
	var txt_mail= $("#txt_mail").val();
	validate_text('#txt_name');
	$.ajax({
        url: "<?php echo $url_add_customer;?>",
        type: "post",
        data: {'customer_name':customer_name,'contact':contact,'phone':phone,'address':address,'txt_mail':txt_mail},
        success: function(data){
            val = $.parseJSON(data);
            $('#customer_id').append($("<option></option>").attr("value",val['cus_id']).attr("selected",true).text(customer_name));                       
			$('#contact').val(contact);
			$('#txt_phone').val(phone);
			$('#customer_add').val(address);
			$('#customer_id').next().val(customer_name);
             document.getElementById("frmvendor").reset();
            HideDialogVendor();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
//for add location
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
            $('#LocationId').append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 

			$('#LocationId').next().val(location_name);
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
 
}
</script>