<?php 					
	$url_new = $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'sales',));//'action'=>'customer-order'
	$url_delete = $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'delete-customer-order',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("SALES_ORDER");?></title>
<div class="right" style="padding:10px; width: 97%">
<div class="wrapper">
  <div style="width:98%; margin:0 auto;">
	 
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
						<?php //echo $tr->translate("ADV_SEARCH");?>
					 <div style="width: 100%;">
						<table style="width: 100%" class="view-table">
							<tr>
								<td>
									<table class="shadow" style="width: 100%" >
										<tr class="height">
											<td><?php echo $tr->translate("INVOICE_NUM");?></td>
											<td width="30%"><?php echo $formFilter->getElement('order');?></td>
											<td><?php echo $tr->translate("AGENT_NAME");?></td>
											<td width="30%"><?php echo $formFilter->getElement('sale_agent_id');?></td>
										</tr>
										<tr class="height">
											<td><?php echo $tr->translate("STATUS")?></td>
											<td><?php echo $formFilter->getElement('status');?></td>
											<td><?php //echo $tr->translate("END_DATE");?></td>
											<td><?php //echo $formFilter->getElement('search_end_date');?></td>
										</tr>
										<tr class="height">
											<td><?php echo $tr->translate("START_DATE")?></td>
											<td><?php echo $formFilter->getElement('search_start_date');?></td>
											<td><?php echo $tr->translate("END_DATE");?></td>
											<td><?php echo $formFilter->getElement('search_end_date');?></td>
										</tr>
										<tr class="height">
											<td colspan="2" class="btn"></td>
											<td class="btn"></td>
											<td class="btn"><input type="submit" value="<?php echo $tr->translate("REFRESH");?>" />
											</td>
										</tr>
										<tr class="height">
											<td colspan="2" class="btn"></td>
											<td class="btn"></td>
											<td class="btn">
												<div class="btn" align="right">
													<?php 
														$formList = new Application_Form_Frmlist();
														echo $formList->showAddBuntton($url_new);
													?>
												</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</div>
						<br/>
			   	  <div class="">
						<div class="head_form">
							<?php echo $tr->translate("SALES_ORDER_LIST_CAP");?>
						</div>
						<div class="contain_form">
							<?php echo $this->list; ?>
						</div><!-- end of .contain_form -->
				</div>
				</form>
	</div>
</div><!-- end wrapper -->
</div><!-- end of .right -->