<?php 					
	$url_new = $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add',));
	$url_delete = $this->url(array('module'=>'sales','controller'=>'customer','action'=>'delete-customer',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("CUSTOMER-LIST");?></title>
<div class="right" style="padding:10px; width: 97%">
<div class="wrapper">
  <div style="width:98%; margin:0 auto;">
	  		<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<table  style="width: 100%">
						<tr>
							<td class="add-edit">
								<table style="width: 100%" class="margin view-table shadow">
									<tr class="height">
										<td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
										<td width="30%"><?php echo $formFilter->getElement('name');?></td>
										<td><?php echo $tr->translate("CON_NAME")."/".$tr->translate("CON_NUM");?></td>
										<td width="30%"><?php echo $formFilter->getElement('phone');?></td>
									</tr>
									<tr class="height">
										<td><?php echo $tr->translate("EMAIL")."/".$tr->translate("WEBSITE");?></td>
										<td><?php echo $formFilter->getElement('email');?></td>
										<td><?php echo $tr->translate("TYPE_PRICE_SM");?></td>
										<td><?php echo $formFilter->getElement('type_price');?></td>
									</tr>
									<tr class="height">
										<td colspan="2" class="btn"></td>
										</td>
										<td class="btn">
										</td>
										<td class="btn"><input type="submit" value="<?php echo $tr->translate("REFRESH");?>" />
									</tr>
									<tr>
										<td colspan="2" class="btn"></td>
										<td class="btn"></td>
										<td class="btn">
											<div class="btn" align="right">
												<?php 
													$formList = new Application_Form_Frmlist();
													echo $formList->showAddBuntton($url_new);
												?>
											</div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
		    <!-- table here -->
		    <br/>
		   <div style="position: relative; clear: both;">
		   	  <div class="">
				<div class="head_form">
					<?php echo $tr->translate("CUSTOMER-LIST");?>
				</div>
				<div class="contain_form">
					<?php echo $this->list; ?>
				</div><!-- end of .contain_form -->
			  </div>
		  </div>
		 </form>
  </div>
</div><!-- end wrapper -->
</div><!-- end of .right -->