<?php 
$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
$url_submit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'update-customer'));
$url_edit =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'index'));
//for view control
$form=$this->customer_frm;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

?>
<title><?php echo $tr->translate("MENU_SALES_CUSTOMER_UPDATE_CUSTOMER");?></title>
<body>
<div class="wrapper">
    <div class="clear"></div>
    <div class="contance">
    </div><!--end of contance-->
    <div class="left">

    </div><!--end of left-->
    <div class="right">
    <form id="frm" action="<?php echo $url_submit;?>" method="post" enctype="multipart/form-data">
    	<div class="contorl-cus">
    	
        	<?php  $frmctrol=$this->control ;?>
        	<?php echo $frmctrol->getElement('New');?>
        	<?php echo $frmctrol->getElement('Update');?>
        	<?php //echo $frmctrol->getElement('Copy');?>
        	<a href="<?php echo $url_edit; ?>" class="cancel">Cancel</a>
        	<input type="button" class='close' name="CloseMe" value="Close Me" onclick="closeMe()" />
<!--         	<a href="javascript:hide_popup('my_popup')" class="closetab"></a> -->
            <!-- tab -->
        </div>
        <!-- blog tabs -->
        <div id="tabs" class="tabs-bottom">
			<ul style="border-top:1px solid #999;">
				<li><a href="#tabs-1"><?php echo $tr->translate("CUSTOMER_INFO");?></a></li>
				<li><a href="#tabs-2"><?php echo $tr->translate("Extra Info");?></a></li>
				<li><a href="#tabs-3"><?php echo $tr->translate("ORDER_HISTORY");?></a></li>
			</ul>
			<div class="tabs-spacer"></div>
			<div id="tabs-1">
				<div class="view-table shadow">
					<div class="head_form">
						<?php echo $tr->translate("Customer info");?>
					</div>
					<div class="contain_form">
					
		        	<table style="width:90%; margin:0 auto;">
		                <tr class="main_info">
		                	<td colspan="2"><?php echo $tr->translate("BASIC");?></td>
		                    <td colspan="2"><?php echo $tr->translate("CUS_ADDRESS");?></td> 
		                </tr>
		                <tr class="height">
		                    <td><?php echo $tr->translate("CUSTOMER_NAME");echo $form->getElement('id');?></td>
		                     <td width="30%"><?php echo $form->getElement('txt_name'); ?></td>
		                    <td><?php echo $tr->translate("CUS_ADDRESS");?></td>
		                    <td rowspan="2" width="30%"><?php echo $form->getElement('txt_address'); ?></td>
		                </tr>
		                <tr class="height">
		                    <td><?php echo $tr->translate("BALANCE");?></td>
		                    <td><?php echo $form->getElement('txt_balance'); ?></td>
		                    <td></td>
		                </tr>
		                <tr class="main_info">
		                	<td colspan="2"><?php echo $tr->translate("CON_NAME");?></td>
		                    <td colspan="2"><?php echo $tr->translate("PURCHASE_INFO");?></td>
		                    
		                </tr>
		               <tr class="height">
		                    <td><?php echo $tr->translate("CON_NAME");?></td>
		                    <td><?php echo $form->getElement('txt_contact_name'); ?></td>
		                    <td><?php echo $tr->translate("TYPE_PRICE_SM");?></td>
		                    <td><?php echo $form->getElement('type_price');?></td>
		                </tr>
		                <tr class="height">
		                    <td><?php echo $tr->translate("PHONE_NUM");?></td>
		                    <td><?php echo $form->getElement('txt_phone'); ?> </td>
		                    <td><?php echo $tr->translate("STATUS");?></td>
		                    <td><div class="select_d">
		                        <?php echo $form->getElement('status');?>
		                        </div>
		                    </td>
		                </tr>
		                  <tr class="height">
		                    <td><?php echo $tr->translate("FAX");?></td>
		                    <td><?php echo $form->getElement('txt_fax'); ?></td>
		                    <td><?php //echo $tr->translate("DISCOUNT-VALUE");?></td>
		                    <td><?php //echo $form->getElement('txt_discount'); ?></td>
		                   
		                </tr>
		                <tr class="height">
		                    <td><?php echo $tr->translate("EMAIL");?></td>
		                    <td><?php echo $form->getElement('txt_mail'); ?></td>
		                    <td></td>
		                </tr>
		                <tr class="height">
		                    <td><?php echo $tr->translate("WEBSITE");?></td>
		                    <td><?php echo $form->getElement('txt_website'); ?></td>
		                    <td></td>
		                    <td></td>
		                </tr>
		                <tr class="main_info">
		                	<td colspan="2"><?php echo $tr->translate("REMARK");?></td>
		                    <td colspan="2"></td>
		                </tr>
		                <tr>
		                    <td></td>
		                    <td width="15%"><?php echo $form->getElement('remark');?></td>
		                    <td></td>
		                    <td></td>
		                </tr>
		            </table>
					</div><!-- end of .contain_form -->
		       </div>
			</div>
			<div id="tabs-2">		
			</div>
			<div id="tabs-3">
				<div class='view-table'>
					<table border='1px' width='100%' style="border:1px solid #ccc;">
						<tr class="head-table">
							<td><?php echo $tr->translate("ORDER");?></td>
							<td><?php echo $tr->translate("ORDER_DATE");?></td>
							<td><?php echo $tr->translate("STATUS");?></td>
							<td><?php echo $tr->translate("TOTAL");?></td>
							<td><?php echo $tr->translate("TOTAL_PAID");?></td>
							<td><?php echo $tr->translate("BALANCE_DUE");?></td>
						</tr>
						<?php 
						$num=0;
						 	for($i=1; $i<=12 ; $i++)
						 	{
						 		$num=1-$num; 
						 		echo"<tr class='row-table{$num}'>";
						 			echo"<td>$i</td>"; 
						 			echo"<td></td>";
						 			echo"<td></td>";
						 			echo"<td></td>";
						 			echo"<td></td>";
						 			echo"<td></td>";
						 		echo"</tr>";
						 	}
						?>
						
					</table>
				</div>
			</div>
		</div>
        <!-- end blog tabs -->
        
        <div class="clear"></div>
    </div><!--end right-->
   </form>
</div><!--end wrapper-->
</body>
</html>
