<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$form=$this->form;
//$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
$url_submit =  $this->url(array('module'=>'product','controller'=>'AdjustStock','action'=>'adjust-price'));
$url_cancel =  $this->url(array('module'=>'product','controller'=>'AdjustStock','action'=>'index'));
?>
<title><?php echo $tr->translate("MENU_PRODUCT_ADJUST_STOCK_ADJUST_PRICE");?></title>
<div class="transfer">
<br/>
	<div class="view-table">
		<div class="head_form">
			<?php echo $tr->translate("ADJUST_PRODUCT_PRICE");?>
		</div>
		<div class="contain_form">
			<form id="orderFrm" action"<?php echo $url_submit;?>" method="post">
			   <div class="btn" align="right">
					    <button type="submit" class="positive" name="save" value='<?php echo $tr->translate("ADJUST");?>'>
					        <img src="<?php echo BASE_URL?>/images/icon/apply2.png" alt=""/>
					       <?php echo $tr->translate("ADJUST"); ?>
					    </button>
					    <a href="<?php echo $url_cancel; ?>" class="negative">
					        <img src="<?php echo BASE_URL?>/images/icon/cross.png" alt=""/>
					        <?php echo $tr->translate("CANCEL"); ?>
					    </a>
			   </div>
					<table>
						  <tr>
							<td valign="top" colspan="2">
								<table class="collape" id="table_order">
									<tr class="row-table1">
										<td class="sub-tdheader"><?php echo $tr->translate("NUM");?></td>
										<td class="sub-tdheader" width='25%'><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
										<td class="sub-tdheader"><?php echo strtoupper($tr->translate("NEW_PRICE"));?></td>
										<td class="sub-tdheader" width='25%'><?php echo strtoupper($tr->translate("OLD_PRICE"));?></td>
									</tr>
					          </table>
								<input type="hidden" id="identity" name="identity" />
								<table>
									<tr>
										<td class="new-row">
											<div class="btn">
												<button class="positive" type="button" id="new_item"  name= "new_followup" value="New">
													&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
												</button>
											</div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</form>
		</div>
	</div>
</div>
<div id="overlay" class="web_dialog_overlay"></div>
<?php $frm_product= $this->form_product;?>
		<div id="dialog" class="web_dialog">
		<form id="frm1">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_ITEM");?>
				<a href="#" id="btnClose" class="cancelDailog"></a>
			</div>
			<table style="width: 100%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("ITEM");?></td>
					<td><?php echo $frm_product->getElement("product_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("ITEM_CODE");?></td>
					<td><?php echo $frm_product->getElement("item_code");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("PRICE");?></td>
					<td><?php echo $frm_product->getElement("item_price");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $frm_product->getElement("remark_order");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addProduct()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancel" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
				</tr>
	       </table>
	     </form>
 </div>
<script>
//action when click on add/delete of followup
var index5 = 0;
var option5 = '<?php echo $this->productOption; ?>';
var locationOption = '<?php echo $this->locationOption; ?>';

var value = '';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var urlPrice = '<?php echo BASE_URL.'/distributor/order/getItemPrice'; ?>';
// add order record
function addRow() {
	index5++; var first = index5;
	template='<tr id="row_order_'+index5+'">';
	var inp = '';
	if(index5 == 1) {
		template+='<td width="5%" class="quater-input">&nbsp;</td>';
	} else {
		template+='<td width="5%" class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		//inp = '<input type="text" style="position: relative;margin-top: -15px; top:-15px; width: 211px;" onchange="AddLocation('+index5+')" class="validate[required] ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" value="'+value+'">';
	}
	template+='<td class="quater-input" width="30%"><select Onchange="getCurrentPrice('+index5+')" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'</select>'+inp+'</td>'; 
	template+='<td class="quater-input" ><input type="text" class="validate[required,custom[number]]" id="new_price_'+index5+'" name="new_price_'+index5+'" /></td>';
	template+='<td class="quater-input" style="width:30%;" ><input type="text" readonly="readonly" id="old_price_'+index5+'" name="old_price_'+index5+'" /></td>';
	
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#orderFrm").validationEngine();
	$("#item_id_"+index5).chosen();
}

//add default row or record when click
$('#new_item').click(addRow);
//add default row or record when ready
jQuery(document).ready(function(){
	addRow();
});

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();	
}

<?php $url_getcurrent_price =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'get-current-price')); ?>
var record_index= 1;
function getCurrentPrice(index){
	item_id = $("#item_id_"+ index).val();
	if(item_id==-1){
		     record_index = index;
			 ShowDialog(true);
	}
	else{
		$.ajax({
	        url: "<?php echo $url_getcurrent_price;?>",
	        type: "post",
	        data: {'item_id':item_id},
	        success: function(data){
	            val = $.parseJSON(data);
	            $("#old_price_"+index).val(val.price);
	            $("#new_price_"+inex).val(val.price);
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });
	}
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
function addProduct(){
	var pro_name = $("#product_name").val();
	var pro_code = $("#item_code").val();
	var price = $("#item_price").val();
	var remark = $("#remark_order").val();
	validate_text('#product_name');
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'price':price,'remark':remark},
	        success: function(data){
	            val = $.parseJSON(data);
	            $('#item_id_'+record_index).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name)); 
	            $('#item_id_'+record_index).trigger("liszt:updated");
	            $("#old_price_"+record_index).val(price);
	            $("#new_price_"+record_index).val(price);

	        	//$('#item_id_'+record_index).next().val(pro_name);
	            document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            alert("Insert Failed!");
	            $("#result").html('There is error while submit');
	        }
	    });	
}

</script>