<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$form=$this->form;
//$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
$url_submit =  $this->url(array('module'=>'product','controller'=>'AdjustStock','action'=>'transfer-stock'));
$url_cancel =  $this->url(array('module'=>'product','controller'=>'AdjustStock','action'=>'index'));

?>
<div class="transfer">
		<br/>
		<div class="view-table">
			<div class="head_form">
				<?php echo $tr->translate("TRANSFER_STOCK");?>
			</div>
			<div class="contain_form">
				<form id="orderFrm" action"<?php echo $url_submit;?>" method="post">
				   <div class="btn" align="right">
						    <button type="submit" class="positive" name="save" value='save'>
						        <img src="<?php echo BASE_URL?>/images/icon/apply2.png" alt=""/>
						       <?php echo $tr->translate("TRANSFER"); ?>
						    </button>
						    <a href="<?php echo $url_cancel; ?>" class="negative">
						        <img src="<?php echo BASE_URL?>/images/icon/cross.png" alt=""/>
						        <?php echo $tr->translate("CANCEL"); ?>
						    </a>
				   </div>
						<table>
							<tr>
								<td valign="top" colspan="2">
									<table class="collape" id="table_order">
										<tr class="row-table1">
											<td class="sub-tdheader"><?php echo $tr->translate("NUM");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
											<td class="sub-tdheader"><?php echo strtoupper($tr->translate("FROM_LOCATION"));?></td>
											<td class="sub-tdheader"><?php echo strtoupper($tr->translate("TO_LOCATION"));?></td>
											<td class="sub-tdheader"><?php echo strtoupper($tr->translate("QTY_TRANSFER"));?></td>
										</tr>
									</table>
									<input type="hidden" id="identity" name="identity" />
									<table>
										<tr>
											<td class="new-row">
												<div class="btn">
													<button class="positive" type="button" id="new_item"  name= "new_followup" value="New">
														&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
													</button>
												</div>
											</td>
										</tr>
									</table>								
								</td>
							</tr>
						</table>
					</form>
			</div>
		</div>
	</div>
	<!-- end new product -->
<div id="overlay" class="web_dialog_overlay"></div>
<?php $frm_product= $this->form;?>
		<div id="dialog" class="web_dialog">
		<form id="frm1">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_ITEM");?>
				<a href="#" id="btnClose" class="cancelDailog"></a>
			</div>
			<table style="width: 95%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("ITEM_NAME");?></td>
					<td><?php echo $frm_product->getElement("txt_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("ITEM_CODE");?></td>
					<td><?php echo $frm_product->getElement("item_code");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("SALE_PRICE");?></td>
					<td><?php echo $frm_product->getElement("price");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $frm_product->getElement("remark_order");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addProduct()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>"/>
						<input id="btnCancel" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
				</tr>
	       </table>
	     </form>
 </div>
 <div id="overlay-location" class="web_dialog_overlay"></div>
		<?php $form_stock = $this->form_addstock; ?>
		<div id="dialog-location" class="web_dialog">
		<form id="frm-location">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_LOCATION");?>
				<a href="#" id="btnCloseLocation" class="cancelDailog"></a>
			</div>
			<table style="width: 95%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("LOCATION_NAME");?></td>
					<td><?php echo $form_stock->getElement("StockName");?></td>
					<td><?php echo $tr->translate("CON_NAME");?></td>
					<td><?php echo $form_stock->getElement("ContactName");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CON_NUM");?></td>
					<td><?php echo $form_stock->getElement("ContactNumber");?></td>
					<td><?php echo $tr->translate("STOCK_ADD");?></td>
					<td><?php echo $form_stock->getElement("location_add");?></td>
				</tr>
				<tr>
					<td colspan="2"></td>
					<td><?php echo $tr->translate("DESC");?></td>
					<td><?php echo $form_stock->getElement("description");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addNewLocation()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btncancel_location" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
					<td colspan="2"></td>
				</tr>
	       </table>
	     </form>
 </div>
  
<script>
//action when click on add/delete of followup
var record_id = 1; 
var from = 1; 
var to = 1;
var index5 = 0;
var option5 = '<?php echo $this->productOption; ?>';
var locationOption = '<?php echo $this->locationOption; ?>';
var tolocation ='<?php echo $this->tolocationOption;?>';

var value_item = '',value_loca_to = '',value_loca_from = '';
//var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
// add order record
function addRow() {
	index5++; var first = index5;
	template='<tr id="row_order_'+index5+'">';
	var inp = '';
	if(index5 == 1) {
		template+='<td class="quater-input">&nbsp;</td>';
	} else {
		template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		//inp = '<input type="text" style="position: relative;margin-top: -15px; top:-15px; width: 211px;" onchange="AddLocation('+index5+')" class="validate[required] ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true" value="">';
	}
	template+='<td class="quater-input"><div class="select_d"><select class="validate[required]" Onchange="ShowPopupProduct('+ index5 + ')" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'</select>'+inp+'</div></td>'; 
	template+='<td class="quater-input"><div class="select_d"><select class="validate[required]" onchange="AddLocation('+ index5 + ')" id="from_location_id_'+index5+'" name="from_location_id_'+index5+'" >'+locationOption+'</select>'+inp+'</div></td>'; 
	template+='<td class="quater-input"><div class="select_d"><select class="validate[required]" onchange="AddLocation('+ index5 + ') "id="to_location_id_'+index5+'" name="to_location_id_'+index5+'" >'+tolocation+'</select>'+inp+'</div></td>'; 
	template+='<td class="quater-input"><input type="text" class="validate[required,custom[number]] input" id="qty_id_'+index5+'" name="qty_id_'+index5+'" /></td>';
	
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#orderFrm").validationEngine();
	if(first == 1){	
		value_loca_to = $("#to_location_id_1 :selected").attr('label');
		value_loca_from = $("#from_location_id_1 :selected").attr('label');
		value_item = $("#item_id_1 :selected").attr('label');
	}else{
		$("select#item_id_"+index5).next().val(value_item);
		$("select#from_location_id_"+index5).next().val(value_loca_from);
		$("select#to_location_id_"+index5).next().val(value_loca_to);
	}
}

//add default row or record when click
$('#new_item').click(addRow);
//add default row or record when ready
jQuery(document).ready(function(){
	addRow();
});

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();	
}

function ShowPopupProduct(index){
	item_id = $("#item_id_"+ index).val();
	record_id = index;
	if(item_id==-1){
		ShowDialog(true);
        
	}
	else{
		getCurrentQuantity(index);	
	}
}

function AddLocation(index){
	var fromlocation_id= $("#from_location_id_"+index).val();
	//var tolocation_id= $("#to_location_id_"+index).val();
	if(fromlocation_id==-1){
		     record_id = index; 
		     form = 1;
		     AddNewLocation(true);
	}
	else{
		getCurrentQuantity(index);
	}	
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
function addProduct(){
	var pro_name = $("#txt_name").val();
	var pro_code = $("#item_code").val();
	var price = $("#price").val();
	var remark = $("#remark_order").val();
	validate_text('#txt_name');
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'price':price,'remark':remark},
	        success: function(data){
	           val = $.parseJSON(data);
	           $('#item_id_'+record_id).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name)); 

        	  // $('#item_id_'+record_id).next().val(pro_name);
	            document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
           
        	   $('#from_location_id_'+record_id).append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 
        	   $('#to_location_id_'+record_id).append($("<option></option>").attr("value",val['LocationId']).attr("selected",false).text(location_name));

          	   //$('#from_location_id_'+record_id).next().val(location_name);
        	   $('#to_location_id_'+record_id).next().val(location_name);
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}

//for get current qyt
<?php $url_getcurrentitem =  $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'get-current-quantity')); ?>
function getCurrentQuantity(index){
	item_id = $("#item_id_"+ index).val();
	location_id = $("#from_location_id_"+ index ).val();
		$.ajax({
		        url: "<?php echo $url_getcurrentitem;?>",
		        type: "post",
		        data: {'item_id':item_id, 'location_id':location_id},
		        success: function(data){
		            //alert(data);
		            val = $.parseJSON(data);
		             var qty =val.qty;
		             if(qty <= 0){
			             alert("Your Product from location will be less then 0\n\n Are You Sure To Transfer?");
			            }
		           // $("#qty_before_"+ index).val(val.qty);
		        },
		        error:function(){
		          // alert("Please Product Name And Location");
		            $("#result").html('There is error while submit');
		        }
		    });
		
	
}
</script>