<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$form=$this->form;
//$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
$url_submit =  $this->url(array('module'=>'product','controller'=>'AdjustStock','action'=>'update-item-price'));
$url_cancel =  $this->url(array('module'=>'product','controller'=>'AdjustStock','action'=>'index'));
$add_price = $this->frm_addprice;
$row_price = $this->pricetype_option;

?>
<title><?php echo $tr->translate("MENU_PRODUCT_ADJUST_STOCK_ADJUST_PRICE");?></title>
<div class="wrapper">
	<div class="right">
	<br/>
		<div class="view-table">
			<div class="head_form">
				<?php echo $tr->translate("ADD_PRODUCT_PRICE");?>
			</div>
			<div class="contain_form">
				<form id="orderFrm" action"<?php echo $url_submit;?>" method="post">.
					<table style="background:#eeeeee; border:1px solid #ccc;">
						<tr>
					 		<td colspan="4" height="40px;"></td>
					 	</tr>
						<tr>
							<td width="10%"></td>
							<td width="20%"><?php echo $tr->translate("ITEM_NAME");?></td>
							<td width="35%"><?php echo $add_price->getElement("pro_id");?></td>
							<td><?php echo $add_price->getElement("id");?></td>
					 	</tr>
					 	<tr>
							<td></td>
							<td><?php echo $tr->translate("DESC");?></td>
							<td><br /><?php echo $add_price->getElement("price_desc");?></td>
							<td></td>
					 	</tr>
					 	<tr>
					 		<td colspan="4" height="40px;"></td>
					 	</tr>
					</table>
				   <div class="btn" align="right">
				   </div>
						<table>
							  <tr>
								<td valign="top" colspan="2">
									<table class="collape" id="table_order">
										<tr class="row-table1">
											<td class="sub-tdheader"><?php echo $tr->translate("DEL");?></td>
											<td class="sub-tdheader"><?php echo $tr->translate("NUM");?></td>
											<td class="sub-tdheader" width='25%'><?php echo $tr->translate("TYPE_PRICE");?></td>
											<td class="sub-tdheader"><?php echo strtoupper($tr->translate("PRICE"));?></td>
											<td class="sub-tdheader" width='25%'><?php echo strtoupper($tr->translate("REMARK_CAP"));?></td>
										</tr>
						          </table>
									<input type="hidden" id="identity" name="identity" />
									<table>
										<tr>
											<td class="new-row">
												<div class="btn">
													<button class="positive" type="button" id="new_item"  name= "new_followup" value="New">
														&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
													</button>
												</div>
											</td>
										</tr>
									</table>
								</td>
								</tr>
								<tr>
									<td colspan="2" align="center">
										<input class="btn_submit" type="submit" name="update" value="<?php echo $tr->translate("UPDATE_CLOSE");?>"></input>
										<input class="btn_submit" type="button" value="Cancel" name="payment" onclick="Cancel()"></input>
									</td>
								</tr>
							
						</table>
					</form>
			</div>
		</div>
	</div>
</div>
<div id="overlay" class="web_dialog_overlay"></div>
<?php $frm_price= $this->frm_price; //echo $frm_price;?>
		<div id="dialog" class="web_dialog">
		<form id="frm1">
			<div class="web_dialog_title" align="center"><?php echo $tr->translate("ADD_NEW_ITEM");?>
				<a href="#" id="btnClose" class="cancelDailog"></a>
			</div>
			<table style="width: 100%; margin:0 auto;" cellpadding="3" cellspacing="0">
				
				<tr>
					<td><?php echo $tr->translate("price_name");?></td>
					<td><?php echo $frm_price->getElement("price_name");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("price_decs");?></td>
					<td><?php echo $frm_price->getElement("price_decs");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("STATUS");?></td>
					<td><?php echo $frm_price->getElement("status");?></td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">
						<input id="btn_add" Onclick="addPriceType()" type="button" value="<?php echo $tr->translate("ADD_NEW");?>" />
						<input id="btnCancel" class="cancelDailog" type="button" value="<?php echo $tr->translate("CANCEL");?>" />
					</td>
				</tr>
	       </table>
	     </form>
 </div>
<script>
//action when click on add/delete of followup
jQuery(document).ready(function(){
	$("#pro_id").chosen();
	var index5 = '<?php echo count($row_price);?>';
	var option5 = '<?php echo $this->price_option; ?>';
	var baseUrl = '<?php echo BASE_URL; ?>';
	var template = '';
	// add Item
	$('#new_item').click(function(){
		index5++;
		var inp = '';
    	
		template='<tr id="row_order_'+index5+'" style="height:33px;">';
		template+='<td class="quater-input" width="2%"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';

		template+='<td class="quater-input" width="3%">'+index5+'</td>';
		template+='<td class="quater-input" width="35%"><select id="type_price_'+index5+'" name="type_price_'+index5+'" >'+option5+'</select>'+inp+'</td>';
		template+='<td class="quater-input"><input type="text" class="validate[required,custom[number]]" id="price_'+index5+'" name="price_'+index5+'" /></td>';
		template+='<td class="quater-input"><input type="text" id="remark_'+index5+'" name="remark_'+index5+'"/></td>';
		
		template+="</tr>";
		$('#table_order').append(template);
		var preIdentity = $('#identity').val();
		$('#identity').val(preIdentity+','+index5);
		$("#orderFrm").validationEngine();
		$("#type_price_"+index5).chosen();
	});

	initList();
	$('#orderFrm').validationEngine();
});

//show row of order item
function initList() {
	var template;
	var optionItem = '<?php echo $this->price_option;?>';
	<?php if(!empty($row_price)) {
		foreach($row_price AS $i=>$r){
			$inx = $i +1;?>
			template='<tr id="row_order_<?php echo $inx;?>" style="height:33px;">';
			if(<?php echo $inx;?> == 1) {
			template+='<td class="quater-input center"></td>';
			} else {
			template+='<td class="quater-input" width="2%"><img onClick="deleteRecord(<?php echo $inx;?>)" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
			}
			template+='<td class="quater-input" width="3%"><?php echo $inx;?></td>';
			template+='<td class="quater-input" width="35%"><select id="type_price_<?php echo $inx;?>" name="type_price_<?php echo $inx;?>" >'+optionItem+'</select></td>';
			template+='<td class="quater-input"><input type="text"  class="validate[required,custom[number]]" id="price_<?php echo $inx;?>" name="price_<?php echo $inx;?>"/></td>';
			template+='<td class="quater-input"><input type="text" type="text" id="remark_<?php echo $inx;?>" name="remark_<?php echo $inx;?>"/></td>';
			template+='</tr>';
			$('#table_order').append(template);

		
			$('#type_price_<?php echo $inx;?>').val('<?php echo $r['type_price'];?>');
			$('#price_<?php echo $inx;?>').val('<?php echo $r['price'];?>');
			$('#remark_<?php echo $inx;?>').val('<?php echo $r['remark']; ?>');
			
			$('#type_price_<?php echo $inx;?>').chosen();

			if(<?php echo $inx;?>!=1) {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+<?php echo $inx;?>);
			} else {$('#identity').val(<?php echo $inx;?>);}
		<?php } }?>
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();	
}

<?php $url_getcurrent_price =  $this->url(array('module'=>'sales','controller'=>'sales-order','action'=>'get-current-price')); ?>
var record_index= 1;
function getCurrentPrice(index){
	item_id = $("#type_price_"+ index).val();
	if(item_id==-1){
		     record_index = index;
			 ShowDialog(true);
	}
	else{
		/*$.ajax({
	        url: "<?php //echo $url_getcurrent_price;?>",
	        type: "post",
	        data: {'item_id':item_id},
	        success: function(data){
	            val = $.parseJSON(data);
	            $("#old_price_"+index).val(val.price);
	            $("#new_price_"+inex).val(val.price);
	        },
	        error:function(){
	            $("#result").html('There is error while submit');
	        }
	    });*/
	}
}
<?php $url_add_price =  $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'add-new-price-type')); ?>
function addPriceType(index){
	var price_name = $("#price_name").val();
	var price_decs = $("#price_decs").val();
	var status = $("#status").val();
	validate_text('#price_name');
	$.ajax({
        url: "<?php echo $url_add_price;?>",
        type: "post",
        data: {'price_name':price_name,'price_decs':price_decs,'status':status},
        success: function(data){
            val = $.parseJSON(data);
            alert(data);
            $('#type_price_'+record_index).append($('<option></option>').attr('value',val['type_id']).attr("selected",true).text(price_name)); 
            $('#type_price_'+record_index).trigger("liszt:updated");

            document.getElementById("frm1").reset();
            HideDialog();
        },
        error:function(){
            alert("Insert Failed!");
            $("#result").html('There is error while submit');
        }
    });	
    
	
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new')); ?>
/*function addProduct(){
	var pro_name = $("#product_name").val();
	var pro_code = $("#item_code").val();
	var price = $("#item_price").val();
	var remark = $("#remark_order").val();
	validate_text('#product_name');
		$.ajax({
	        url: "<?php //echo $url_add_new;?>",
	        type: "post",
	        data: {'pro_name':pro_name,'pro_code':pro_code,'price':price,'remark':remark},
	        success: function(data){
	            val = $.parseJSON(data);
	            $('#item_id_'+record_index).append($('<option></option>').attr('value',val['pid']).attr("selected",true).text(pro_name)); 
	            $('#item_id_'+record_index).trigger("liszt:updated");
	            $("#old_price_"+record_index).val(price);
	            $("#new_price_"+record_index).val(price);

	        	//$('#item_id_'+record_index).next().val(pro_name);
	            document.getElementById("frm1").reset();
	            HideDialog();
	        },
	        error:function(){
	            alert("Insert Failed!");
	            $("#result").html('There is error while submit');
	        }
	    });	
}*/
function Cancel(){
	var comfir= confirm("តើអ្នកពិតជាចង់ចាកចេញរឺ? ");
	if(comfir==true){
		window.open("<?php echo BASE_URL;?>/product/adjust-stock/price","_parent");
	}
	
}
</script>